[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[doc]
title = "Stability Platform Contracts"
ignore = ["./src/test/**/*.sol"]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
