[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc_version = "0.8.23"

[profile.lite]
optimizer = false

[doc]
title = "Stability Platform Contracts"
ignore = ["./src/test/**/*.sol"]

[fmt]
int_types = "short"
ignore = ["./src/integrations/**/*.sol"]
multiline_func_header = "params_first"

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
polygon = { key = "${ETHERSCAN_API_KEY}", chain = 137  }
