name: test

on:
  push:
    branches:
      - main
  pull_request: { }
  workflow_dispatch: { }


env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Forge test and coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        env:
          POLYGON_RPC_URL: ${{secrets.POLYGON_RPC_URL}}
        id: test

      - name: Run Forge coverage
        run: |
          forge coverage --report lcov
        env:
          POLYGON_RPC_URL: ${{secrets.POLYGON_RPC_URL}}
        id: coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}

      - name: Show contract sizes
        run: NO_COLOR=1 forge build --sizes | grep -v '| 0.' >> $GITHUB_STEP_SUMMARY
